name: Deploy MERN App to EC2

on:
  push:
    branches: [ master ]  # Trigger when code is pushed to the 'master' branch (or change it to 'main' if needed)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        # Ensure EC2_HOST is set before running ssh-keyscan
        if [ -z "${{ secrets.EC2_HOST }}" ]; then
          echo "EC2_HOST is not set!"
          exit 1
        fi
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2 instance
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Navigate to the project folder on EC2
          cd ${{ secrets.EC2_PATH }}

          # Pull latest code from the master branch
          git pull origin master

          # Install backend dependencies
          npm install --prefix server

          # Install frontend dependencies and build
          npm install --prefix client
          npm run build --prefix client

          # Restart the backend using PM2 (or start it if not running)
          pm2 restart mern-app || pm2 start server/index.js --name mern-app
        EOF
